apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sm-book-web
  name: sm-book-web
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-book-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sm-book-web
    spec:
      containers:
        - image: akilan/sm-web:v2
          name: sm-web
          env:
            - name: "BOOK_SERVICE"
              value: "http://sm-book-api:5000"
            - name: "REVIEW_SERVICE"
              value: "http://sm-review-api:7000"
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sm-book-web
  name: sm-book-web
  namespace: demo
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sm-book-web
  type: NodePort
status:
  loadBalancer: {}
