apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sm-review-api
  name: sm-review-api
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-review-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sm-review-api
    spec:
      containers:
        - image: akilan/sm-review-api:v2
          name: sm-review-api
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sm-review-api
  name: sm-review-api
  namespace: demo
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: sm-review-api
  type: NodePort
status:
  loadBalancer: {}
